name: generate_fastapi CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run flake8.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Lint
        run: |
            make lint

  unittest-coverage:
    name: Run unittest and generate code coverage report.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.8 for unitttests.
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Run unittests
        run: |
            make PLATFORM=ci test
            bash <(curl -s https://codecov.io/bash)
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
